const mongoose = require("mongoose");

const complaintNotificationSchema = mongoose.Schema(
  {
    type: { type: String, required: true },
    desc: { type: String, required: true },
    businessId: { type: mongoose.Schema.Types.ObjectId, required: true },
    missingCrops: {
      missingCropsId: { type: mongoose.Schema.Types.ObjectId },
    },
    complaint: {
      complaintId: { type: mongoose.Schema.Types.ObjectId },
    },
    request: {
      requestId: { type: mongoose.Schema.Types.ObjectId },
    },
    autuGeneratedServiceRequest: {
      autoGeneratedServiceId: { type: mongoose.Schema.Types.ObjectId },
    },
    serviceRequest: {
      productId: { type: mongoose.Schema.Types.ObjectId },
      businessDesc: { type: String, default: "Service Request Sent To Admin" },
      adminDesc: {
        type: String,
        default: "New Store Product Service Request Received",
      },
      serviceRequestFor: { type: String, default: "New Product" },
      status: {
        type: String,
        default: "pending",
        enum: ["pending", "approved", "rejected"],
      },
      businessReaded: { type: Boolean, default: false },
      adminReaded: { type: Boolean, default: false },
    },
    readed: { type: Boolean, default: false },
  },
  {
    timestamps: true,
  }
)

 const complaintNotification = mongoose.model('business_complaint_notification', complaintNotificationSchema)

module.exports = complaintNotification