const mongoose = require("mongoose");

const complaintNotificationSchema = mongoose.Schema({ 
    type:{type:String, required: true},
    desc:{type:String, required:true},    
    businessId: { type: mongoose.Schema.Types.ObjectId, required: true },
    missingCrops: {
        missingCropsId: {type: mongoose.Schema.Types.ObjectId}
    },
    complaint: {
        complaintId: {type: mongoose.Schema.Types.ObjectId }
    },
    request: {
        requestId: {type: mongoose.Schema.Types.ObjectId }
    },
    autuGeneratedServiceRequest: {
        autoGeneratedServiceId: {type: mongoose.Schema.Types.ObjectId }
    },
    readed: {type: Boolean, default: false}
}, {
     timestamps: true
 });

 const complaintNotification = mongoose.model('business_complaint_notification', complaintNotificationSchema)

module.exports = complaintNotification